### ISSUE TITLE
GOAL: Scaffold out your APIs

### ISSUE THREAD

**Issue by ecumene** [IsabelMcIlroy/KnittingProjectManager#8]
- [x] #9
- [x] Make an API for projects

<img width="1382" alt="Screen Shot 2022-10-01 at 10 58 09 AM" src="https://user-images.githubusercontent.com/6249465/193411773-3b3edecf-a92a-4992-9169-55026fa47890.png">

**Comment by IsabelMcIlroy** [comment]
![image](https://user-images.githubusercontent.com/73035117/193901276-53d8256d-5c49-4ed8-96c1-e3d4a6282630.png)

**Comment by ecumene** [comment]
A string could work. Maybe separate them with commas:

`#FA8907,#FA8907,#FA8907,`

**Comment by IsabelMcIlroy** [comment]
Excellent - that is what I was thinking but wasn't sure if that would work.
